repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: ["--fix"]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        files: \.(py|pyi)$
        types: [python]
        args: [--fix]

      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        files: \.(py|pyi)$
        types: [python]

      - id: basedpyright
        name: basedpyright
        entry: uv run basedpyright
        language: system
        files: \.(py|pyi)$
        types: [python]

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]
        files: ^src/
        pass_filenames: false
        args: ["--all"]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        language: system
        types: [rust]
        files: ^src/
        pass_filenames: false
        args: ["--tests", "--", "-D", "warnings"]

      - id: pytest
        language: system
        name: pytest
        pass_filenames: false
        entry: uv run pytest

      - id: docs-build
        name: docs build
        entry: uv run --group docs mkdocs build
        files: ^docs/
        pass_filenames: false
        language: system
        args: ["--strict"]
