[package]
name = "tarsio-core"
version = "0.3.1"
edition = "2024"

[lib]
name = "_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1.5.0"
pyo3 = { version = "0.27.2", features = ["generate-import-lib"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
