[package]
name = "tarsio-core"
version = "0.4.3"
edition = "2024"

[lib]
name = "tarsio_core"
crate-type = ["cdylib"]


[dependencies]
bytes = "1.11.1"
simdutf8 = "0.1.5"
thiserror = "2.0"
pyo3 = { version = "0.28.0", features = ["extension-module", "generate-import-lib"] }
smallvec = "1"
rustc-hash = "2"
parking_lot = "0.12"

[dev-dependencies]
proptest = "1.10.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
